### ISSUE TITLE
When validating an object, passing an object will return wrong message

### ISSUE THREAD

**Issue by elevatebart** [mdvorscak/validate-params#1]
``` js
function MyObject(items){
    Validator.assert.arg(items, 'object')
    //rest of the code
}
var a = new MyObject(['itema', 'itemb']);
```
will return the following error

`Expected type "object" but it was type "object"`

**Comment by mdvorscak** [comment]
The issue is that the object is an array which has a special validation, the message should really be:

Expected type "object" but it was type "array"

Issue is caused by: https://github.com/mdvorscak/validate-params/blob/master/index.js#L40
